#include <pybind11/pybind11.h>

#include <pybind11/native_enum.h>
#include <pybind11/operators.h>
#include <pybind11/stl.h>

#include <SFML/Window/Keyboard.hpp>

namespace py = pybind11;

void bind_keyboard(py::module_& m) {
    // Keyboard namespace
    auto keyboard = m.def_submodule("Keyboard", "Keyboard input handling");
    
    py::native_enum<sf::Keyboard::Key>(keyboard, "Key", "enum.IntEnum",
    R"(Key codes.

The enumerators refer to the "localized" key; i.e. depending on the layout set
by the operating system, a key can be mapped to Y or Z.
)"
    )
        .value("UNKNOWN", sf::Keyboard::Key::Unknown)
        .value("A", sf::Keyboard::Key::A)
        .value("B", sf::Keyboard::Key::B)
        .value("C", sf::Keyboard::Key::C)
        .value("D", sf::Keyboard::Key::D)
        .value("E", sf::Keyboard::Key::E)
        .value("F", sf::Keyboard::Key::F)
        .value("G", sf::Keyboard::Key::G)
        .value("H", sf::Keyboard::Key::H)
        .value("I", sf::Keyboard::Key::I)
        .value("J", sf::Keyboard::Key::J)
        .value("K", sf::Keyboard::Key::K)
        .value("L", sf::Keyboard::Key::L)
        .value("M", sf::Keyboard::Key::M)
        .value("N", sf::Keyboard::Key::N)
        .value("O", sf::Keyboard::Key::O)
        .value("P", sf::Keyboard::Key::P)
        .value("Q", sf::Keyboard::Key::Q)
        .value("R", sf::Keyboard::Key::R)
        .value("S", sf::Keyboard::Key::S)
        .value("T", sf::Keyboard::Key::T)
        .value("U", sf::Keyboard::Key::U)
        .value("V", sf::Keyboard::Key::V)
        .value("W", sf::Keyboard::Key::W)
        .value("X", sf::Keyboard::Key::X)
        .value("Y", sf::Keyboard::Key::Y)
        .value("Z", sf::Keyboard::Key::Z)
        .value("NUM0", sf::Keyboard::Key::Num0)
        .value("NUM1", sf::Keyboard::Key::Num1)
        .value("NUM2", sf::Keyboard::Key::Num2)
        .value("NUM3", sf::Keyboard::Key::Num3)
        .value("NUM4", sf::Keyboard::Key::Num4)
        .value("NUM5", sf::Keyboard::Key::Num5)
        .value("NUM6", sf::Keyboard::Key::Num6)
        .value("NUM7", sf::Keyboard::Key::Num7)
        .value("NUM8", sf::Keyboard::Key::Num8)
        .value("NUM9", sf::Keyboard::Key::Num9)
        .value("ESCAPE", sf::Keyboard::Key::Escape)
        .value("LCONTROL", sf::Keyboard::Key::LControl)
        .value("LSHIFT", sf::Keyboard::Key::LShift)
        .value("LALT", sf::Keyboard::Key::LAlt)
        .value("LSYSTEM", sf::Keyboard::Key::LSystem)
        .value("RCONTROL", sf::Keyboard::Key::RControl)
        .value("RSHIFT", sf::Keyboard::Key::RShift)
        .value("RALT", sf::Keyboard::Key::RAlt)
        .value("RSYSTEM", sf::Keyboard::Key::RSystem)
        .value("MENU", sf::Keyboard::Key::Menu)
        .value("LBRACKET", sf::Keyboard::Key::LBracket)
        .value("RBRACKET", sf::Keyboard::Key::RBracket)
        .value("SEMICOLON", sf::Keyboard::Key::Semicolon)
        .value("COMMA", sf::Keyboard::Key::Comma)
        .value("PERIOD", sf::Keyboard::Key::Period)
        .value("APOSTROPHE", sf::Keyboard::Key::Apostrophe)
        .value("SLASH", sf::Keyboard::Key::Slash)
        .value("BACKSLASH", sf::Keyboard::Key::Backslash)
        .value("GRAVE", sf::Keyboard::Key::Grave)
        .value("EQUAL", sf::Keyboard::Key::Equal)
        .value("HYPHEN", sf::Keyboard::Key::Hyphen)
        .value("SPACE", sf::Keyboard::Key::Space)
        .value("ENTER", sf::Keyboard::Key::Enter)
        .value("BACKSPACE", sf::Keyboard::Key::Backspace)
        .value("TAB", sf::Keyboard::Key::Tab)
        .value("PAGEUP", sf::Keyboard::Key::PageUp)
        .value("PAGEDOWN", sf::Keyboard::Key::PageDown)
        .value("END", sf::Keyboard::Key::End)
        .value("HOME", sf::Keyboard::Key::Home)
        .value("INSERT", sf::Keyboard::Key::Insert)
        .value("DELETE", sf::Keyboard::Key::Delete)
        .value("ADD", sf::Keyboard::Key::Add)
        .value("SUBTRACT", sf::Keyboard::Key::Subtract)
        .value("MULTIPLY", sf::Keyboard::Key::Multiply)
        .value("DIVIDE", sf::Keyboard::Key::Divide)
        .value("LEFT", sf::Keyboard::Key::Left)
        .value("RIGHT", sf::Keyboard::Key::Right)
        .value("UP", sf::Keyboard::Key::Up)
        .value("DOWN", sf::Keyboard::Key::Down)
        .value("NUMPAD0", sf::Keyboard::Key::Numpad0)
        .value("NUMPAD1", sf::Keyboard::Key::Numpad1)
        .value("NUMPAD2", sf::Keyboard::Key::Numpad2)
        .value("NUMPAD3", sf::Keyboard::Key::Numpad3)
        .value("NUMPAD4", sf::Keyboard::Key::Numpad4)
        .value("NUMPAD5", sf::Keyboard::Key::Numpad5)
        .value("NUMPAD6", sf::Keyboard::Key::Numpad6)
        .value("NUMPAD7", sf::Keyboard::Key::Numpad7)
        .value("NUMPAD8", sf::Keyboard::Key::Numpad8)
        .value("NUMPAD9", sf::Keyboard::Key::Numpad9)
        .value("F1", sf::Keyboard::Key::F1)
        .value("F2", sf::Keyboard::Key::F2)
        .value("F3", sf::Keyboard::Key::F3)
        .value("F4", sf::Keyboard::Key::F4)
        .value("F5", sf::Keyboard::Key::F5)
        .value("F6", sf::Keyboard::Key::F6)
        .value("F7", sf::Keyboard::Key::F7)
        .value("F8", sf::Keyboard::Key::F8)
        .value("F9", sf::Keyboard::Key::F9)
        .value("F10", sf::Keyboard::Key::F10)
        .value("F11", sf::Keyboard::Key::F11)
        .value("F12", sf::Keyboard::Key::F12)
        .value("F13", sf::Keyboard::Key::F13)
        .value("F14", sf::Keyboard::Key::F14)
        .value("F15", sf::Keyboard::Key::F15)
        .value("PAUSE", sf::Keyboard::Key::Pause)
        .export_values()
        .finalize();

        // I suspect this shares a module name with Key

//     py::native_enum<sf::Keyboard::Scan>(keyboard, "Scan", "enum.IntEnum",
//     R"(Scancodes.

// The enumerators are bound to a physical key and do not depend on the keyboard
// layout used by the operating system. Usually, the AT-101 keyboard can be used
// as reference for the physical position of the keys. 
// )")
//         .value("UNKNOWN", sf::Keyboard::Scan::Unknown)
//         .value("A", sf::Keyboard::Scan::A)
//         .value("B", sf::Keyboard::Scan::B)
//         .value("C", sf::Keyboard::Scan::C)
//         .value("D", sf::Keyboard::Scan::D)
//         .value("E", sf::Keyboard::Scan::E)
//         .value("F", sf::Keyboard::Scan::F)
//         .value("G", sf::Keyboard::Scan::G)
//         .value("H", sf::Keyboard::Scan::H)
//         .value("I", sf::Keyboard::Scan::I)
//         .value("J", sf::Keyboard::Scan::J)
//         .value("K", sf::Keyboard::Scan::K)
//         .value("L", sf::Keyboard::Scan::L)
//         .value("M", sf::Keyboard::Scan::M)
//         .value("N", sf::Keyboard::Scan::N)
//         .value("O", sf::Keyboard::Scan::O)
//         .value("P", sf::Keyboard::Scan::P)
//         .value("Q", sf::Keyboard::Scan::Q)
//         .value("R", sf::Keyboard::Scan::R)
//         .value("S", sf::Keyboard::Scan::S)
//         .value("T", sf::Keyboard::Scan::T)
//         .value("U", sf::Keyboard::Scan::U)
//         .value("V", sf::Keyboard::Scan::V)
//         .value("W", sf::Keyboard::Scan::W)
//         .value("X", sf::Keyboard::Scan::X)
//         .value("Y", sf::Keyboard::Scan::Y)
//         .value("Z", sf::Keyboard::Scan::Z)
//         .value("NUM1", sf::Keyboard::Scan::Num1)
//         .value("NUM2", sf::Keyboard::Scan::Num2)
//         .value("NUM3", sf::Keyboard::Scan::Num3)
//         .value("NUM4", sf::Keyboard::Scan::Num4)
//         .value("NUM5", sf::Keyboard::Scan::Num5)
//         .value("NUM6", sf::Keyboard::Scan::Num6)
//         .value("NUM7", sf::Keyboard::Scan::Num7)
//         .value("NUM8", sf::Keyboard::Scan::Num8)
//         .value("NUM9", sf::Keyboard::Scan::Num9)
//         .value("NUM0", sf::Keyboard::Scan::Num0)
//         .value("ENTER", sf::Keyboard::Scan::Enter)
//         .value("ESCAPE", sf::Keyboard::Scan::Escape)
//         .value("BACKSPACE", sf::Keyboard::Scan::Backspace)
//         .value("TAB", sf::Keyboard::Scan::Tab)
//         .value("SPACE", sf::Keyboard::Scan::Space)
//         .value("HYPHEN", sf::Keyboard::Scan::Hyphen)
//         .value("EQUAL", sf::Keyboard::Scan::Equal)
//         .value("LBRACKET", sf::Keyboard::Scan::LBracket)
//         .value("RBRACKET", sf::Keyboard::Scan::RBracket)
//         .value("BACKSLASH", sf::Keyboard::Scan::Backslash)
//         .value("SEMICOLON", sf::Keyboard::Scan::Semicolon)
//         .value("APOSTROPHE", sf::Keyboard::Scan::Apostrophe)
//         .value("GRAVE", sf::Keyboard::Scan::Grave)
//         .value("COMMA", sf::Keyboard::Scan::Comma)
//         .value("PERIOD", sf::Keyboard::Scan::Period)
//         .value("SLASH", sf::Keyboard::Scan::Slash)
//         .value("F1", sf::Keyboard::Scan::F1)
//         .value("F2", sf::Keyboard::Scan::F2)
//         .value("F3", sf::Keyboard::Scan::F3)
//         .value("F4", sf::Keyboard::Scan::F4)
//         .value("F5", sf::Keyboard::Scan::F5)
//         .value("F6", sf::Keyboard::Scan::F6)
//         .value("F7", sf::Keyboard::Scan::F7)
//         .value("F8", sf::Keyboard::Scan::F8)
//         .value("F9", sf::Keyboard::Scan::F9)
//         .value("F10", sf::Keyboard::Scan::F10)
//         .value("F11", sf::Keyboard::Scan::F11)
//         .value("F12", sf::Keyboard::Scan::F12)
//         .value("F13", sf::Keyboard::Scan::F13)
//         .value("F14", sf::Keyboard::Scan::F14)
//         .value("F15", sf::Keyboard::Scan::F15)
//         .value("F16", sf::Keyboard::Scan::F16)
//         .value("F17", sf::Keyboard::Scan::F17)
//         .value("F18", sf::Keyboard::Scan::F18)
//         .value("F19", sf::Keyboard::Scan::F19)
//         .value("F20", sf::Keyboard::Scan::F20)
//         .value("F21", sf::Keyboard::Scan::F21)
//         .value("F22", sf::Keyboard::Scan::F22)
//         .value("F23", sf::Keyboard::Scan::F23)
//         .value("F24", sf::Keyboard::Scan::F24)
//         .value("CAPSLOCK", sf::Keyboard::Scan::CapsLock)
//         .value("PRINTSCREEN", sf::Keyboard::Scan::PrintScreen)
//         .value("SCROLLLOCK", sf::Keyboard::Scan::ScrollLock)
//         .value("PAUSE", sf::Keyboard::Scan::Pause)
//         .value("INSERT", sf::Keyboard::Scan::Insert)
//         .value("HOME", sf::Keyboard::Scan::Home)
//         .value("PAGEUP", sf::Keyboard::Scan::PageUp)
//         .value("DELETE", sf::Keyboard::Scan::Delete)
//         .value("END", sf::Keyboard::Scan::End)
//         .value("PAGEDOWN", sf::Keyboard::Scan::PageDown)
//         .value("RIGHT", sf::Keyboard::Scan::Right)
//         .value("LEFT", sf::Keyboard::Scan::Left)
//         .value("DOWN", sf::Keyboard::Scan::Down)
//         .value("UP", sf::Keyboard::Scan::Up)
//         .value("NUMLOCK", sf::Keyboard::Scan::NumLock)
//         .value("NUMPADDIVIDE", sf::Keyboard::Scan::NumpadDivide)
//         .value("NUMPADMULTIPLY", sf::Keyboard::Scan::NumpadMultiply)
//         .value("NUMPADMINUS", sf::Keyboard::Scan::NumpadMinus)
//         .value("NUMPADPLUS", sf::Keyboard::Scan::NumpadPlus)
//         .value("NUMPADEQUAL", sf::Keyboard::Scan::NumpadEqual)
//         .value("NUMPADENTER", sf::Keyboard::Scan::NumpadEnter)
//         .value("NUMPADDECIMAL", sf::Keyboard::Scan::NumpadDecimal)
//         .value("NUMPAD1", sf::Keyboard::Scan::Numpad1)
//         .value("NUMPAD2", sf::Keyboard::Scan::Numpad2)
//         .value("NUMPAD3", sf::Keyboard::Scan::Numpad3)
//         .value("NUMPAD4", sf::Keyboard::Scan::Numpad4)
//         .value("NUMPAD5", sf::Keyboard::Scan::Numpad5)
//         .value("NUMPAD6", sf::Keyboard::Scan::Numpad6)
//         .value("NUMPAD7", sf::Keyboard::Scan::Numpad7)
//         .value("NUMPAD8", sf::Keyboard::Scan::Numpad8)
//         .value("NUMPAD9", sf::Keyboard::Scan::Numpad9)
//         .value("NUMPAD0", sf::Keyboard::Scan::Numpad0)
//         .value("NONUSBACKSLASH", sf::Keyboard::Scan::NonUsBackslash)
//         .value("APPLICATION", sf::Keyboard::Scan::Application)
//         .value("EXECUTE", sf::Keyboard::Scan::Execute)
//         .value("MODECHANGE", sf::Keyboard::Scan::ModeChange)
//         .value("HELP", sf::Keyboard::Scan::Help)
//         .value("MENU", sf::Keyboard::Scan::Menu)
//         .value("SELECT", sf::Keyboard::Scan::Select)
//         .value("REDO", sf::Keyboard::Scan::Redo)
//         .value("UNDO", sf::Keyboard::Scan::Undo)
//         .value("CUT", sf::Keyboard::Scan::Cut)
//         .value("COPY", sf::Keyboard::Scan::Copy)
//         .value("PASTE", sf::Keyboard::Scan::Paste)
//         .value("VOLUMEMUTE", sf::Keyboard::Scan::VolumeMute)
//         .value("VOLUMEUP", sf::Keyboard::Scan::VolumeUp)
//         .value("VOLUMEDOWN", sf::Keyboard::Scan::VolumeDown)
//         .value("MEDIAPLAYPAUSE", sf::Keyboard::Scan::MediaPlayPause)
//         .value("MEDIASTOP", sf::Keyboard::Scan::MediaStop)
//         .value("MEDIANEXTTRACK", sf::Keyboard::Scan::MediaNextTrack)
//         .value("MEDIAPREVIOUSTRACK", sf::Keyboard::Scan::MediaPreviousTrack)
//         .value("LCONTROL", sf::Keyboard::Scan::LControl)
//         .value("LSHIFT", sf::Keyboard::Scan::LShift)
//         .value("LALT", sf::Keyboard::Scan::LAlt)
//         .value("LSYSTEM", sf::Keyboard::Scan::LSystem)
//         .value("RCONTROL", sf::Keyboard::Scan::RControl)
//         .value("RSHIFT", sf::Keyboard::Scan::RShift)
//         .value("RALT", sf::Keyboard::Scan::RAlt)
//         .value("RSYSTEM", sf::Keyboard::Scan::RSystem)
//         .value("BACK", sf::Keyboard::Scan::Back)
//         .value("FORWARD", sf::Keyboard::Scan::Forward)
//         .value("REFRESH", sf::Keyboard::Scan::Refresh)
//         .value("STOP", sf::Keyboard::Scan::Stop)
//         .value("SEARCH", sf::Keyboard::Scan::Search)
//         .value("FAVORITES", sf::Keyboard::Scan::Favorites)
//         .value("HOMEPAGE", sf::Keyboard::Scan::HomePage)
//         .value("LAUNCHAPPLICATION1", sf::Keyboard::Scan::LaunchApplication1)
//         .value("LAUNCHAPPLICATION2", sf::Keyboard::Scan::LaunchApplication2)
//         .value("LAUNCHMAIL", sf::Keyboard::Scan::LaunchMail)
//         .value("LAUNCHMEDIASELECT", sf::Keyboard::Scan::LaunchMediaSelect)
//         .export_values()
//         .finalize();
    
    // TODO
    keyboard.def("is_key_pressed", py::overload_cast<sf::Keyboard::Key>(&sf::Keyboard::isKeyPressed), "Check if a key is currently pressed");
    
}
